name: Checks

on:
  pull_request:
  push:
    branches:
      - master
      - release

jobs:
  tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Checking types
        run: npm run typecheck
      - name: Lint
        run: npm run lint
